name: Build iOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.7'
    - name: Clean Flutter Build
      run: flutter clean
    - name: Install CocoaPods
      run: sudo gem install cocoapods
    - name: Accept Xcode License
      run: sudo xcodebuild -license accept
    - run: flutter pub get
    - run: cd ios && pod install --repo-update --verbose && cd ..
    - name: Disable Signing and Capabilities
      run: |
        PBXPROJ=ios/Runner.xcodeproj/project.pbxproj
        sed -i '' -e '/DEVELOPMENT_TEAM/d' -e '/CODE_SIGN_IDENTITY/d' -e '/PROVISIONING_PROFILE/d' -e '/CODE_SIGN_STYLE/d' -e '/Push Notifications/d' $PBXPROJ
        echo "CODE_SIGN_STYLE = Manual;" >> $PBXPROJ
        echo "CODE_SIGN_IDENTITY = \"\";" >> $PBXPROJ
        echo "PROVISIONING_PROFILE_SPECIFIER = \"\";" >> $PBXPROJ
        echo "DEVELOPMENT_TEAM = \"\";" >> $PBXPROJ
    - name: Build with xcodebuild
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -destination 'generic/platform=iOS' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    - name: Zip IPA
      run: |
        cd ../build/ios/iphoneos
        mkdir Payload
        mv Runner.app Payload/
        zip -r hello_world.ipa Payload
    - uses: actions/upload-artifact@v4
      with:
        name: hello-ipa
        path: build/ios/iphoneos/hello_world.ipa
