name: Build iOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.7'
    - run: flutter clean
    - name: Install CocoaPods
      run: sudo gem install cocoapods
    - name: Accept Xcode License
      run: sudo xcodebuild -license accept
    - run: flutter pub get
    - run: cd ios && pod install --repo-update --verbose && cd ..
    - name: Disable Signing in Xcode
      run: |
        PBXPROJ=ios/Runner.xcodeproj/project.pbxproj
        sed -i '' -E 's/(DEVELOPMENT_TEAM = ).*/\1"";/g' $PBXPROJ
        sed -i '' -E 's/(CODE_SIGN_IDENTITY = ).*/\1"";/g' $PBXPROJ
        sed -i '' -E 's/(PROVISIONING_PROFILE_SPECIFIER = ).*/\1"";/g' $PBXPROJ
        sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' $PBXPROJ
    - run: flutter build ios --release --no-codesign --verbose
    - name: Zip IPA
      run: |
        cd build/ios/iphoneos
        mkdir Payload
        mv Runner.app Payload/
        zip -r hello_world.ipa Payload
    - uses: actions/upload-artifact@v4
      with:
        name: hello-ipa
        path: build/ios/iphoneos/hello_world.ipa
